services:
  bird-db:
    # image: mysql:latest
    # restart: always
    # ports:
    #   - "3306:3306"
    # environment:
    #   - MYSQL_ROOT_PASSWORD=passw
    # volumes:
    #   - ./db-init:/docker-entrypoint-initdb.d/
    image: urfu-mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=passw

  bird-twitter:
    image: urfu-twitter:latest
    restart: always
    ports:
      - "9001:9001"
    environment:
      - SERVICE_TWITTER_PORT=9001
      - URL_DB_TWITTER=jdbc:mysql://urfu-java-bird-db-1:3306/twitter?serverTimezone=UTC&useLegacyDatetimeCode=false
      - USERNAME_DB=root
      - PASSWORD_DB=passw
      - SERVICE_UMS_HOST_URL=http://urfu-java-bird-db-1
      - SERVICE_UMS_PORT=9000
    depends_on:
      - bird-db

  bird-ums:
    image: urfu-ums:latest
    restart: always
    ports:
      - "9000:9000"
    environment:
      - SERVICE_UMS_PORT=9000
      - USERNAME_DB=root
      - PASSWORD_DB=passw
      - URL_DB_TWITTER=jdbc:mysql://urfu-java-bird-db-1:3306/ums?serverTimezone=UTC&useLegacyDatetimeCode=false
    depends_on:
      - bird-db