services:
  bird-db:
    # image: mysql:latest
    # restart: always
    # ports:
    #   - "3306:3306"
    # environment:
    #   - MYSQL_ROOT_PASSWORD=passw
    # volumes:
    #   - ./db-init:/docker-entrypoint-initdb.d/
    image: urfu-mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=passw

  bird-twitter:
    image: urfu-twitter:latest
    restart: always
    ports:
      - "9001:9001"
    depends_on:
      - bird-db

  bird-ums:
    image: urfu-ums:latest
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - bird-db