## Server
server:
  port: ${SERVICE_TWITTER_PORT}

## MySQL
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://10.10.200.120:3306/twitter?serverTimezone=UTC&useLegacyDatetimeCode=false
    url: ${URL_DB_TWITTER}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}

ums:
  # host: http://localhost
  host: ${SERVICE_UMS_HOST_URL}
  # port: 9000
  port: ${SERVICE_UMS_PORT}
  paths:
    user: /users/user

